name: "Check License"
on:
  push:

jobs:
  decode-secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print decoded secret
        run: echo "${{ secrets.OCTOPUS_SERVER_BASE64_LICENSE }}" | base64 -d
